# This is an auto-generated Django model module created by ogrinspect.
from django.contrib.gis.db import models

class masterbiketrails(models.Model):
    objectid = models.IntegerField()
    source = models.CharField(max_length=20)
    side = models.CharField(max_length=13)
    type = models.CharField(max_length=50)
    jurisdicti = models.CharField(max_length=10)
    active = models.IntegerField()
    notes = models.CharField(max_length=250)
    name = models.CharField(max_length=50)
    fac_id = models.CharField(max_length=50)
    miles = models.FloatField()
    width = models.IntegerField()
    direction = models.CharField(max_length=10)
    grade = models.CharField(max_length=1)
    speed = models.IntegerField()
    fac_qual = models.CharField(max_length=50)
    lighted = models.CharField(max_length=1)
    opperation = models.CharField(max_length=50)
    proposed = models.CharField(max_length=1)
    arterial = models.CharField(max_length=1)
    conn_gap = models.CharField(max_length=1)
    stops = models.IntegerField()
    class_ = models.CharField(max_length=12)
    road_name = models.CharField(max_length=35)
    road_numb = models.CharField(max_length=10)
    road_code = models.CharField(max_length=2)
    road_speed = models.IntegerField()
    road_comm = models.CharField(max_length=1)
    lane_numb = models.IntegerField()
    lane_width = models.IntegerField()
    lane_dir = models.CharField(max_length=10)
    lane_type = models.CharField(max_length=24)
    shld_width = models.FloatField()
    shld_type = models.CharField(max_length=50)
    shld_rumb = models.CharField(max_length=1)
    shld_park = models.CharField(max_length=24)
    shld_bus = models.CharField(max_length=1)
    shape_leng = models.FloatField()
    maintainer = models.CharField(max_length=35)
    install_yr = models.CharField(max_length=16)
    install_or = models.CharField(max_length=32)
    suitabilit = models.CharField(max_length=24)
    shld_date = models.DateField()
    shld_plow = models.CharField(max_length=3)
    shld_drain = models.CharField(max_length=3)
    road_aadt = models.IntegerField()
    road_hcadt = models.CharField(max_length=1)
    surf_type = models.CharField(max_length=25)
    surf_qaul = models.CharField(max_length=25)
    geom = models.LineStringField(srid=26915)
    objects = models.GeoManager()

# Auto-generated `LayerMapping` dictionary for masterbiketrails model
masterbiketrails_mapping = {
    'objectid' : 'OBJECTID',
    'source' : 'SOURCE',
    'side' : 'SIDE',
    'type' : 'TYPE',
    'jurisdicti' : 'JURISDICTI',
    'active' : 'ACTIVE',
    'notes' : 'NOTES',
    'name' : 'NAME',
    'fac_id' : 'FAC_ID',
    'miles' : 'MILES',
    'width' : 'WIDTH',
    'direction' : 'DIRECTION',
    'grade' : 'GRADE',
    'speed' : 'SPEED',
    'fac_qual' : 'FAC_QUAL',
    'lighted' : 'LIGHTED',
    'opperation' : 'OPPERATION',
    'proposed' : 'PROPOSED',
    'arterial' : 'ARTERIAL',
    'conn_gap' : 'CONN_GAP',
    'stops' : 'STOPS',
    'class_' : 'CLASS',
    'road_name' : 'ROAD_NAME',
    'road_numb' : 'ROAD_NUMB',
    'road_code' : 'ROAD_CODE',
    'road_speed' : 'ROAD_SPEED',
    'road_comm' : 'ROAD_COMM',
    'lane_numb' : 'LANE_NUMB',
    'lane_width' : 'LANE_WIDTH',
    'lane_dir' : 'LANE_DIR',
    'lane_type' : 'LANE_TYPE',
    'shld_width' : 'SHLD_WIDTH',
    'shld_type' : 'SHLD_TYPE',
    'shld_rumb' : 'SHLD_RUMB',
    'shld_park' : 'SHLD_PARK',
    'shld_bus' : 'SHLD_BUS',
    'shape_leng' : 'SHAPE_LENG',
    'maintainer' : 'MAINTAINER',
    'install_yr' : 'INSTALL_YR',
    'install_or' : 'INSTALL_OR',
    'suitabilit' : 'SUITABILIT',
    'shld_date' : 'SHLD_DATE',
    'shld_plow' : 'SHLD_PLOW',
    'shld_drain' : 'SHLD_DRAIN',
    'road_aadt' : 'ROAD_AADT',
    'road_hcadt' : 'ROAD_HCADT',
    'surf_type' : 'SURF_TYPE',
    'surf_qaul' : 'SURF_QAUL',
    'geom' : 'LINESTRING',
}
